services:
  tl_database:
    container_name: tl_database_mariadb
    image: mariadb:11
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks: [tl-network]
    restart: unless-stopped

  tl_dbms:
    container_name: tl_dbms_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: tl_database
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on: [tl_database]
    networks: [tl-network]

  tl_backend:
    container_name: tl_backend_wp
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    environment:
      - WP_DB_HOST=tl_database:3306
      - WP_DB_NAME=${DB_DATABASE}
      - WP_DB_USER=${DB_USER}
      - WP_DB_PASSWORD=${DB_PASSWORD}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    networks: [tl-network]
    depends_on: [tl_database]
    restart: unless-stopped

networks:
  tl-network:
    driver: bridge

volumes:
  db-data:
  logs:
